version: '3.8'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress
  # Wordpress
  nginx:
    depends_on:
      - php
    image: nginx:latest
    #ports:
    #  - '80:80'
    restart: always
    volumes:
      - ./git-clone:/var/www/wordpress
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress
  php:
    depends_on:
      - db
    build: 
      dockerfile: ./php/dockerfile
    volumes:
      - ./git-clone:/var/www/wordpress
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress

  varnish:
    depends_on:
      - nginx
    image: varnish:latest
    ports:
      - 80:80
    restart: always
    user: root
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"

    networks:
      - wordpress

  redis:
    depends_on:
      - db
    image: redis:latest
    restart: always
    networks:
      - wordpress


networks:
  wordpress:
volumes:
  db_data:
